version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/projet-sls-mobile
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: "Dependency ionic & firebase tools"
        command: npm firebase-tools
    - run:
        name: "Install npm dependencies"
        command: npm install
    - run:
        name: "Firebase cloud function"
        command: cd functions && npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
        - functions/node_modules
    - run:
        name: "Firebase deploy"
        command: firebase deploy --non-interactive --token $FIREBASE_TOKEN
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
