version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/projet-sls-mobile
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "public/package.json" }}-{{ checksum "functions/package.json" }}
    - run:
        name: "Dependency firebase tools"
        command: npm add firebase-tools
    - run:
        name: "Install npm dependencies"
        command: cd public && npm install
    - run:
        name: "Firebase cloud function"
        command: cd functions && npm install
    - save_cache:
        key: dependency-cache-{{ checksum "public/package.json" }}-{{ checksum "functions/package.json" }}
        paths:
        - public/node_modules
        - functions/node_modules
    - run:
        name: "Linter cloud function"
        command: cd functions && npm run lint
    - run:
        name: "Build cloud function"
        command: cd functions && npm run build
    - run:
        name: "Add config"
        command: npx firebase functions:config:set mailgun.key="$MAILGUN_API"
    - run:
        name: "Firebase deploy"
        command: npx firebase deploy --non-interactive --token $FIREBASE_TOKEN
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
